// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {define} from '../models';

export function ConnectionCreate(arg1:define.Connection):Promise<define.H>;

export function ConnectionList():Promise<define.H>;

export function Greet(arg1:string):Promise<string>;
